# setting
theme: jekyll-theme-cayman
title: EIDE Manual
description: A manual for vscode eide plug-in
keyword: 'keil,c51,stm32,sdcc,arm gcc,ide'
url: 'https://marketplace.visualstudio.com/items?itemName=CL.eide'

# footer
footer:
  since: 2020

# author
author: 'cl'